### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by joakim** [gliese1337/PrattParser.js#5]
Hi! Has this been abandoned? I'm looking at libraries for Pratt parsing, and this looks very nice.

**Comment by gliese1337** [comment]
Nope! I haven't had a need to work on it in a while, but it's definitely not abandoned. Let me know if you encounter any issues, and I'll see what I can do about fixing them!

**Comment by joakim** [comment]
Cool, thanks! Appreciate the explanations in the README, this is number 1 on my list so far :)
